---
sidebar: sidebar
permalink: protection-security-resources.html
keywords: netapp, solutions, data management, what's new, updates, change log
summary: Additional technical reports related to data protection and security. 
---
= Additional resources for data protection and security
:icons: font
:imagesdir: ./media/

[.lead]
Check out the links below to access technical reports related to data protection and security.

== NVA-1143: NetApp HCI - NIST security controls for FISMA with HyTrust for multitenant infrastructure - NVA design and deployment
Arvind Ramakrishnan, Abhinav Singh, NetApp

NVA-1143 describes how NetApp HCI can be designed and deployed to meet National Institute of Standards and Technology (NIST) SP 800-53 Revision 4 Security and Privacy controls, which are crucial for private cloud infrastructures and multitenant deployments.

link:https://www.netapp.com/pdf.html?item=/media/17065-nva1143pdf.pdf[NVA-1143: NetApp HCI - NIST security controls for FISMA with HyTrust for multitenant infrastructure - NVA design and deployment^]

== TR-4320: NetApp E-Series and Commvault Data Platform V11 - Reference architecture and storage best practices
Akash Gupta, NetApp 
Girish Chanchlani, Commvault

TR-4320 outlines the reference architecture and best practices when using NetApp E-Series storage in a Commvault Data Platform V11 environment. Commvault and NetApp have jointly developed this reference architecture to provide guidance for Commvault Data Platform V11 deployments with NetApp E-Series storage that will accelerate time to application for this solution.

link:https://www.netapp.com/pdf.html?item=/media/17042-tr4320pdf.pdf[TR-4320: NetApp E-Series and Commvault Data Platform V11 - reference architecture and storage best practices^]

== TR-4471: E-Series and EF-Series reference architecture and storage best practices with Veeam Backup & Replication 9.5
Akash Gupta, NetApp
Shawn Lieu (Americas), Stefan Renner (EMEA), and Michael Cade (Performance), Veeam

TR-4471 outlines the reference architecture and best practices when using NetApp E-Series storage in a Veeam Backup & Replication 9.5 environment.

link:https://www.netapp.com/pdf.html?item=/media/17159-tr4471pdf.pdf[TR-4471: E-Series and EF-Series reference architecture and storage best practices with Veeam Backup & Replication 9.5^]

== TR-4704: Deploying Veritas NetBackup with NetApp E-Series storage
Akash Gupta and Principled Technologies, NetApp

TR-4704 describes deployment of Veritas NetBackup on NetApp E-Series storage.

link:https://www.netapp.com/pdf.html?item=/media/16433-tr-4704pdf.pdf[TR-4704: Deploying Veritas NetBackup with NetApp E-Series storage^]